### ISSUE TITLE
Controls Leds

### ISSUE THREAD

**Issue by RitaLee79** [konsumer/beatstep#4]
Hi there,

i'd like to know if you are able to switch on/off led of controls buttons. I'm trying to use some of the controls as toggles to map new functions to the pads. It would be great if I could use led on/off to indicate this state.
The selected controls are configured as note/toggles but led commands do not work. Do you know if this is even possible?

Thanks

**Comment by RitaLee79** [comment]
Hi, it's me again :)

The problem was that I did all my test on Stop button... and that is the only one that cannot be turned on.
I have tried this code

```py

led_off = Template('F0 00 20 6B 7F 42 02 00 10 $cc 00 F7')
led_on = Template('F0 00 20 6B 7F 42 02 00 10 $cc $vv F7')

controls = ['58', '59', '5A', '5B', '5C', '5D', '5E', '5F']
colors = ['01', '10', '11']
for cont in controls:
    for col in colors:
        led_msg = led_on.substitute(cc=cont, vv=col)
        send_msg(led_msg)
        time.sleep(1)`
```

and now I can answer my question.
They react to the three colors but only have theese colors appearing:

stop - no color possible
cntl/sec - red blue magenta
ext sync - blue
recall - blue
store - red
shift - blue
chan - blue

**Comment by konsumer** [comment]
Sorry t took me so long to get back to you. I saw this initially, but was very busy at the time, and forgot to come back to the issue.

My library is js-based (not python)  and it's been a while since I worked on it, so I can't remember all the sysex messages I used on it. I got the initial format of the sysex messages from [this blogpost](https://www.untergeek.de/2014/11/taming-arturias-beatstep-sysex-codes-for-programming-via-ipad/). Your findings seem about right. The controller doesn't allow us to set everything to all possible values (which is one of the challenges I originally worked around with my little reworked sequencer thing) so it makes sense that it only gives us a subset of the options.

I will close this issue, since it looks like you answered your question, but feel free to comment more, if you need more help or have other findings that should go here.
